#!/bin/sh

# A dwm_bar function to print the weather from wttr.in
# Joe Standring <git@joestandring.com>
# GNU GPLv3

# Dependencies: curl

# Change the value of LOCATION to match your city
dwm_weather() {

		# LOCATION=Rio+de+Janeiro+Brazil
		DATA=$(curl -s 'wttr.in/?format=%c%C+%t\n&lang=pt-br')
		echo "$DATA"
}

dwm_weather
