#!/bin/sh

# A dwm_bar function to read the battery level and status
# Joe Standring <git@joestandring.com>
# GNU GPLv3

dwm_battery () {
    # Change BAT1 to whatever your battery is identified as. Typically BAT0 or BAT1
    CHARGE=$(cat /sys/class/power_supply/BAT1/capacity)
    STATUS=$(cat /sys/class/power_supply/BAT1/status)
	BATTERY=$(bluetooth-headset-battery-level $(bluetoothctl info | awk '/^Device/ {print $2}'))
    if [ "$IDENTIFIER" = "unicode" ]; then
        if [ "$STATUS" = "Charging" ]; then
            printf " %s%%s\n" "$CHARGE" "+"
		elif [ "$STATUS" = "Full" ] || [ "$STATUS" = "Unknown" ]; then
			printf " %s%\n" "$CHARGE"
        else
            printf " %s%%s\n" "$CHARGE" "-"
        fi
    else
        printf " %s%%\n" "$CHARGE"
    fi
#    if [ $CHARGE -le 95 ]; then
#		notify-send -u critical "Bateria em 5%"
#    fi
}

dwm_battery

