#!/bin/sh

# Change BAT1 to whatever your battery is identified as. Typically BAT0 or BAT1
CHARGE=$(cat /sys/class/power_supply/BAT1/capacity)
STATUS=$(cat /sys/class/power_supply/BAT1/status)

if [ "$STATUS" = "Charging" ]; then
	printf " %s%% %s\n" "$CHARGE" "+"
elif [ "$STATUS" = "Full" ] || [ "$STATUS" = "Unknown" ]; then
	printf " %s%%\n" "$CHARGE"
else
	printf " %s%% %s\n" "$CHARGE" "-"

	if [ "$CHARGE" -le "30" ]; then
		notify-send -u critical "Bateria em ${CHARGE}%"
	fi
fi
