#!/bin/sh

# A dwm_bar module to display the current backlight brighness with xbacklight
# Joe Standring <git@joestandring.com>
# GNU GPLv3

#Dependencies: brightnessctl

dwm_backlight () {
    actual=$(brightnessctl g)
    max=$(brightnessctl m)
    bright=$((actual * 100 / max))
    printf " %i%%\n" "$bright"
}

dwm_backlight
