#!/bin/dash
dwm_bluetooth () {
		name=$(bluetoothctl info | grep 'Name' | cut -d : -f 2)
		connected=$(bluetoothctl info | grep 'Connected:' | grep -o 'no\|yes')
		powered=$(bluetoothctl show | grep Powered | grep -o 'no\|yes')

		if [ "$connected" = "yes" ]; then
				if [ "$name" = " LE_WH-1000XM3" ] || [ "$name" = " WH-1000XM3" ]; then
						printf " XM3"
				else
						printf " $name"
				fi
		elif [ "$powered" = "yes" ]; then
						printf ""
		else
						printf ""
		fi

		printf "%s\n" "$SEP2"
}

dwm_bluetooth
